services:
  sqlserver:
    container_name: sqlserver
    image: mcr.microsoft.com/mssql/server
    ports:
      - "1433:1433"
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=yourStrongPassword12#
    volumes:
      - sqldata:/var/opt/mssql
    networks:
      - eventhub_network

  api_app:
    container_name: eventhub_api
    image: nikolay984/eventhub-api_app
    ports:
      - "5000:8080"
    volumes:
      - appdata:/app/data
    networks:
      - eventhub_network
    depends_on:
      - sqlserver

  angular_app:
    container_name: eventhub_frontend
    image: nikolay984/eventhub-angular_app
    ports:
      - "4200:80"
    networks:
      - eventhub_network
    depends_on:
      - api_app

volumes:
  sqldata:
  appdata:
networks:
  eventhub_network: